name: strong_grip_prints_admin
description: A new Flutter project.

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: 3.0.0
  built_collection: 5.1.1
  built_value: 8.4.0
  cached_network_image: 3.2.1
  equatable: 2.0.3
  # firebase_auth: 4.2.0
  # firebase_auth_platform_interface: 6.11.4
  # firebase_auth_web: 5.2.0
  flutter_animate: 1.0.0
  flutter_cache_manager: 3.3.0
  font_awesome_flutter: 10.1.0
  from_css_color: 2.0.0
  google_fonts: 3.0.1
  google_sign_in: 5.4.0
  google_sign_in_ios: 5.4.0
  google_sign_in_platform_interface: 2.2.0
  google_sign_in_web: 0.10.2
  intl: 0.17.0
  json_path: 0.4.1
  json_serializable: 6.3.1
  page_transition: 2.0.4
  plugin_platform_interface: 2.1.3
  provider: 6.0.4
  rxdart: 0.27.4
  shared_preferences: 2.0.15
  sign_in_with_apple: 4.1.0
  sign_in_with_apple_platform_interface: 1.0.0
  sign_in_with_apple_web: 1.0.1
  sqflite: 2.2.0+2
  timeago: 3.2.2
  url_launcher: 6.1.5
  # cloud_firestore: ^4.3.1
  # firebase_storage: ^3.0.8
  image_picker: ^0.8.4
  firebase_core: ^2.4.1
  firebase_storage: ^11.0.10
  cloud_firestore: ^4.3.1
  flutter_launcher_icons: ^0.11.0
  expandable: ^5.0.1


dev_dependencies:
  build_runner: 2.2.0
  built_value_generator: 8.4.0

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_icons:
  image_path: "assets/images/logo_black.jpg" 
  android: true
  #   - assets/videos/
  #   - assets/audios/
  #   - assets/lottie_animations/
  #   - assets/rive_animations/
  #   - assets/pdfs/
  