// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaW-4j2bsURQTxs1TZp2fOvqnN9D2Lxss',
    appId: '1:446778914478:web:1a28329ec1b2b04f7f9f3f',
    messagingSenderId: '446778914478',
    projectId: 'thesis-962c6',
    authDomain: 'thesis-962c6.firebaseapp.com',
    databaseURL: 'https://thesis-962c6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'thesis-962c6.appspot.com',
    measurementId: 'G-MHEJSGKP13',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtQI_VquElKtdGpHswf8GqkWVM1o8u3lc',
    appId: '1:446778914478:android:a041e47d24edf5247f9f3f',
    messagingSenderId: '446778914478',
    projectId: 'thesis-962c6',
    databaseURL: 'https://thesis-962c6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'thesis-962c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9txBm-FTiCPHYb_bday6I6DuQr4Qw36U',
    appId: '1:446778914478:ios:fb88d0fe4abc2a417f9f3f',
    messagingSenderId: '446778914478',
    projectId: 'thesis-962c6',
    databaseURL: 'https://thesis-962c6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'thesis-962c6.appspot.com',
    iosClientId: '446778914478-sca4irjksv5lfmg3chdlh0vqp8glp7oj.apps.googleusercontent.com',
    iosBundleId: 'com.example.strongGripPrintsAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9txBm-FTiCPHYb_bday6I6DuQr4Qw36U',
    appId: '1:446778914478:ios:fb88d0fe4abc2a417f9f3f',
    messagingSenderId: '446778914478',
    projectId: 'thesis-962c6',
    databaseURL: 'https://thesis-962c6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'thesis-962c6.appspot.com',
    iosClientId: '446778914478-sca4irjksv5lfmg3chdlh0vqp8glp7oj.apps.googleusercontent.com',
    iosBundleId: 'com.example.strongGripPrintsAdmin',
  );
}
